config/routes.rb
Rails.application.routes.draw do

  root 'countries#index'

  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
   
      resources :countries
      resources :users do
        resources :votes
      end
    
    

  
 

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :votes
	has_many :users, through: :votes

	def total_score
	  votes.sum(:points)
	end

	def votes_by_user(user)
		Vote.find_by(user: user, country: self) || Vote.new(:points => 0)
	end
end
 

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
  before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }
 	has_many :votes
  has_many :countries, through: :votes

	# Returns the hash digest of the given string.
  	def User.digest(string)
   	 	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
   	 	BCrypt::Password.create(string, cost: cost)
    end

   	#Returns a random token.
  	def User.new_token
  		SecureRandom.urlsafe_base64
  	end
  	
  	#Remembers a user in the database for use in persistent sessions. 
  	def remember
  		self.remember_token = User.new_token
  		update_attribute(:remember_digest, User.digest(remember_token))
  	end

  	# Returns true if the given token matches the digest.
  	def authenticated?(remember_token)
  		return false if remember_digest.nil?
    	BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end

  	#Forgets a user.
  	def forget
  		update_attribute(:remember_digest, "nil")
  	end

	  def give_points(amount, country)
		  vote = Vote.find_or_create_by(user: self, country: country) 
      vote.points = amount
      vote.save
    end



end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :country
	belongs_to :user

	scope :has_points, -> { where("points is not null") }
  	scope :has_no_points, -> { where(points: nil) } 

  	def points?
  	  !points.blank?
    end

  	def self.get_points_for_country_and_user(country, user)
  		Vote.where(country: country, user: user).last
  	end 

    def give_points(amount, country)
		vote = Vote.find_or_create_by(user: self, country: country) 
      	vote.points = amount
      vote.save
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception
  include SessionsHelper 
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController



	def index
		@countries = Country.all
		@countries = Country.all.sort {|a,b| a.total_score <=> b.total_score}.reverse
	end

	def show
		@country = Country.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
  		 params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_to user
  	else
  		flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@countries = Country.all
  end

  def help
  end

  def about
  end

  def contact
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :correct_user,   only: [:show]

	def index
		@users = User.all
		@countries = Country.all.sort {|a,b| a.total_score <=> b.total_score}.reverse
	end

	def show
		@user = User.find(params[:id])
		possible_points = (0..12).to_a - [9] - [11]

		@points_options = []
		possible_points.each do |value|
			@points_options.push([value, value])
		end

		@countries = Country.all

		checks = Hash.new

		@countries_for_table = []

		@countries.each do |country|
			country_for_row = Hash.new
			country_for_row["country"] = country
			country_for_row["vote"] = country.votes_by_user(@user)

			points = country_for_row["vote"].points

			if points == 12
				checks[12] = country
			elsif points == 10
				checks[10] = country
			elsif points == 8
				checks[8] = country
			end

			@countries_for_table.push(country_for_row)
		end


		@countries_for_table.each do |c|
			row_possible_points = possible_points.clone

			if checks[12] && checks[12] != c["country"]
				row_possible_points = row_possible_points - [12]
			end

			if checks[10] && checks[10] != c["country"]
				row_possible_points = row_possible_points - [10]
			end

			if checks[8] && checks[8] != c["country"]
				row_possible_points = row_possible_points - [8]
			end

			c["points_options"] = row_possible_points
		end
	end

	 def new
	  	@user = User.new
	  end

	def create  
	  	@user = User.new(user_params)  
	  	if @user.save
	      log_in @user 
	  		flash[:success] = "Welcome to 12points!"
	  		redirect_to @user
	  	else	
	  		render 'new'
	  	end
  	end

  	private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController	

  def create
    u = User.find(params[:user_id])
    v = u.votes.create(params.require(:vote).permit(:points, :country_id))
    redirect_to user_path(u)
  end

  def update
    vote = Vote.find(params[:id])
    u = User.find(params[:user_id])

    if vote.update_attributes(vote_params)
      flash[:success] = "Punktzahl korrigiert."
      redirect_to user_path(u)
    else
      flash[:error] = "Punktzahl konnte nicht korrigiert werden."
      render action: :edit
    end 
  end

  private 

  def vote_params
    params[:vote].permit(:points, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

def avatar_url(user, size)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

end

app/helpers/countries_helper.rb
module CountriesHelper

def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end	

end

app/helpers/sessions_helper.rb
module SessionsHelper

def log_in(user)
		session[:user_id] = user.id 
	end

	# Remembers a user in a persistent session.
  	def remember(user)
  	  user.remember
   	  cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
  	end	

	# Returns the user corresponding to the remember token cookie.
  	def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

    def current_user?(user)
    	user==current_user
    end

  	#Returns true if the user is logged in, false otherwise.
  	def logged_in?
  		!current_user.nil?
  	end

  	#Forgets a persistent session. 

  	def forget(user)
  		user.forget
  		cookies.delete(:user_id)
  		cookies.delete(:remember_token)
  	end

  	#Logs out the current user
  	def log_out
  		forget(current_user)
  		session.delete(:user_id)
  		@current_user = nil
  	end

end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end	
end

app/views/countries/index.html.erb
<h1>Eurovision Song Contest 2016</h1>



<div class="wrapper">

<table>
	<% @countries.each do |country| %>
	<tr>
		<td><%= country.name %></td>
		<td><%= country.total_score %></td>
	</tr>
	<% end %>	

</table>

</div>

<li> <%= link_to "Sign Up", new_user_path%> </li>

app/views/countries/show.html.erb
<h1><%= @country.name %></h1>

<h4>Punkte</h4>
<table>
	<% @country.votes.each do |vote| %>
	<tr>
		<td><%= vote.user.name %></td>
		<td><%= vote.points %></td>
	</tr>
	<% end %>
</table>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "DOUZE POINTS", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        
        <% if logged_in? %>
          <li class="gravatar">
                    <%= image_tag avatar_url(current_user, 20) %> 
          </li>
          <li class="divider"></li>
          <li> <%= link_to "Profile", current_user %></li>
    
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %> </li>
              <li class="divider"></li>
          
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Douze Points</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   
</head>
<body>

	<%= render 'layouts/header' %>

	<% flash.each do |type, message| %>
	<div class="alert flash <%= type %>">
		<%= message %>
	</div>	
	<% end %>

<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %> 

app/views/users/index.html.erb
<h1>Eurovision Song Contest 2016</h1>



<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for User.new do |f| %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form_control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form_control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form_control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form_control' %>

			<%= f.submit "Account erstellen", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

<div class="wrapper">

<p> Bereits dabei mit Fähnchen in der Hand: 

<table>
<tr>
<% @users.each do |user| %>
		<td><%= user.name %></td>
		<td><%= gravatar_for user, size: 50 %></td>
	</tr>
<% end %>	

</p>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Anmeldung') %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for User.new do |f| %>
		<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name, class: 'form_control' %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form_control' %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form_control' %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation, class: 'form_control' %>

			<%= f.submit "Account erstellen", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %></h1>

<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Teilnehmerland</th>
    <th>Punkte</th>
    <th>Abstimmen</th>
  </tr>
  <% @countries_for_table.each do |c| %>
    <tr>
      <td> <%= c["country"].name %> </td>
      <td> <%= c["vote"].points %> </td>
      <td>
        <%= form_for [@user, c["vote"]] do |f| %>
          <%= f.hidden_field :country_id, :value => c["country"].id %>
          <%= f.select :points, 
            options_for_select(c["points_options"], c["vote"].points)%>
          <%= f.submit("Abstimmen") %>
        <% end %>
      </td>
    </tr>
  <% end %>

 </table>